# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_urlt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='post',
            name='D_O_B',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Degree',
            field=models.CharField(default=False, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='Experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Hospital',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='No_of_Clinics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Specialization',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='University',
            field=models.CharField(default=False, max_length=120),
        ),
    ]
